Linear Regression - Diabetes Dataset
Diabetes dataset is one of the datasets available in sklearn. The diabetes dataset consists of 10 physiological variables (age, sex, weight, blood pressure) measure on 442 patients, and an indication of disease progression after one year.
You are given a Training dataset csv file with X train and Y train data. As studied in lecture, your task is to come up with Linear Regression training algorithm and thus predictions for the test dataset given.
Read Instructions carefully -
1. Use Linear Regression(in scikit learn) as a training algorithm and submit results predicted by that.
2. Files are in csv format, use genfromtxt function in numpy to load data from csv file. Similarly you can use savetxt function to save data into a file.
3. Submit a csv file with only predictions for X test data. File should not have any headers and should only have one column i.e. predictions.  Also prediction values in file should be upto **5** decimal places.
4. Upon submission of predictions, the score you will get is based on coefficient of determination.

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [2]:
data=np.genfromtxt("diabetes_train.csv",delimiter=',')

In [3]:
x_train=data[:,:-1]
y_train=data[:,-1]

In [4]:
linReg = LinearRegression()

In [5]:
linReg.fit(x_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

In [7]:
linReg.score(x_train,y_train)

0.4957208055805604

In [8]:
y_pred = linReg.predict(x_train)

In [9]:
y_pred[:10]

array([271.80601321,  67.74312487,  97.62639376, 217.73083979,
       161.85116331,  76.61540802, 185.8637718 , 169.48651056,
        50.32993631, 221.73035041])

In [10]:
linReg.coef_,linReg.intercept_

(array([  21.73408096, -256.66866675,  569.60940087,  303.63233545,
        -833.11088526,  525.74313633,  136.07129167,  140.89458927,
         731.44498492,   53.32119133]), 150.702574894566)

# Now Loading Up Test Data

In [12]:
test_data=np.genfromtxt("diabetes_test.csv",delimiter=',')

In [14]:
y_predic=linReg.predict(test_data)

In [15]:
y_predic

array([105.52974799, 105.8039198 , 178.60857225,  79.3828781 ,
        52.95868706,  98.87263854, 150.71755448,  34.86515216,
       113.13535727, 161.50184038, 135.8615611 ,  94.71592222,
       138.48094422, 141.37441723, 158.76862662, 171.65288616,
       106.44835654, 103.92659639,  95.38693889, 167.40118092,
       166.53426278, 101.53464712, 252.45035972, 147.02258547,
       214.78906632, 161.27557106, 210.61315228,  71.78091585,
       189.65032431, 206.6134259 , 219.98643455, 168.80192534,
       116.84846127, 178.74399639,  77.03247418,  59.54633214,
       111.5673781 , 156.95186739, 154.59591259, 198.94457493,
       115.53884017, 153.46699024,  84.96179518, 113.70337192,
       142.14155617, 147.31040378,  82.78072358,  77.89237327,
       128.99006192, 261.58712282, 213.31187775, 243.98791257,
       167.68132094, 183.69712124, 166.85926884, 202.11440188,
       220.39235543, 172.40288024, 176.60897931, 109.04656567,
       276.37789836,  90.99941821, 289.37221147, 119.56

In [16]:
np.savetxt("y_pred_diabaties.csv",y_predic,delimiter=",",fmt="%0.5f")